FROM node:20-alpine AS base

FROM base AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app
COPY package.json pnpm-lock.yaml* ./
RUN npm install -g pnpm && pnpm install --frozen-lockfile

FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
ARG SERVICE_PATH
RUN npm install -g pnpm && cd ${SERVICE_PATH} && pnpm build

FROM base AS runner
WORKDIR /app
ENV NODE_ENV=production
ARG SERVICE_PATH
COPY --from=builder /app/${SERVICE_PATH}/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/packages ./packages
ENV SERVICE_PORT=4000
EXPOSE 4000
CMD ["node", "dist/index.js"]
